spring:
  batch:
    job:
      enabled: true
  datasource:
    jdbc-url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO
    username: sa
    password: 
    driverClassName: org.h2.Driver